image: python:3.7-slim

stages:
  - check
  - test
  - release

quality:
  stage: check
  before_script:
    - pip install -e .
    - pip install black pylint mypy
  script:
    - pylint pylint_flask_sqlalchemy && mypy pylint_flask_sqlalchemy && black --diff pylint_flask_sqlalchemy
  allow_failure: false
  except:
    - schedules

test:
  stage: test
  before_script:
    - pip install -e .
  script:
    - pylint tests/example.py --load-plugins pylint_flask_sqlalchemy
  except:
    - schedules

pypi:
  stage: release
  before_script:
    - pip install twine
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
