image: python:3.7-slim

stages:
  - check
  - test
  - release

quality:
  stage: check
  script:
    - pip install black pylint mypy
    - pylint pylint_flask_sqlalchemy && mypy pylint_flask_sqlalchemy && black --diff pylint_flask_sqlalchemy
  allow_failure: false
  except:
    - schedules

test:
  stage: test
  before_script:
    - python setup.py develop
  script:
    - pytest
  except:
    - schedules
  artifacts:
    name: "coverage-${CI_COMMIT_REF_NAME}"
    when: always
    untracked: true
    expire_in: 1 week
    paths:
      - htmlcov
    reports:
      junit: report.xml

pypi:
  stage: release
  before_script:
    - pip install twine
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
