#!/bin/sh
#
# post-commit hook
# MAJ du changelog grace à gitchangelog et ammend du commit
export PYTHONIOENCODING=UTF-8 LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8
echo "post-commit changelog..."
. "/PATH/TO/VENV/bin/activate"
gitchangelog > CHANGELOG.md
res=$(git status --porcelain | grep CHANGELOG.md | wc -l)
if [ "$res" -gt 0 ]; then
    git add CHANGELOG.md
    git commit --amend --no-edit
fi
exit
