name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pylint_flask_sqlalchemy[dev]
        run: pip install .[dev]
      - name: Pylint
        run: pylint pylint_flask_sqlalchemy
      - name: Mypy
        run: mypy pylint_flask_sqlalchemy
      - name: Black
        run: black --diff pylint_flask_sqlalchemy
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pylint_flask_sqlalchemy[dev]
        run: pip install .[dev]
      - name: Run tests
        run: pytest
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pylint_flask_sqlalchemy
        run: pip install  .
      - name: Run pylint with pylint_flask_sqlalchemy on example.py
        run: |
          pylint tests/example.py --load-plugins pylint_flask_sqlalchemy