name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pylint_flask_sqlalchemy[dev]
        run: pip install .[dev]
      - name: Pylint
        run: pylint pylint_flask_sqlalchemy
      - name: Mypy
        run: mypy pylint_flask_sqlalchemy
      - name: Black
        run: black --diff pylint_flask_sqlalchemy

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9"]
        flask_sqlalchemy: ["2.4.4", "2.5.1"]
        sqlalchemy: ["1.3.24", "1.4.25"]
        exclude:
          # sqlalchemy 1.4 support comes in flask_sqlalchemy 2.5
          - flask_sqlalchemy: "2.4.4"
            sqlalchemy: "1.4.25"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install pylint_flask_sqlalchemy[dev]
        run: |
          pip install -e .[dev]
          pip install --upgrade flask_sqlalchemy==${{ matrix.flask_sqlalchemy }}
          pip install --upgrade sqlalchemy==${{ matrix.sqlalchemy }}
      - name: Run tests
        run: pytest

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pylint_flask_sqlalchemy
        run: |
          pip install  -e .
      - name: Run pylint with pylint_flask_sqlalchemy
        run: |
          pylint --load-plugins pylint_flask_sqlalchemy *.py
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install build
        run: |
          pip install build
      - name: Run build
        run: |
          python -m build
